[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver2"
version_provider = "pep621"
update_changelog_on_bump = true
changelog_incremental = false
changelog_file = "CHANGELOG.md"
major_version_zero = true
